### ISSUE TITLE
crash with Error: Service urn:upnp-org:serviceId:AVTransport not provided by device

### ISSUE THREAD

**Issue by addadi** [mas94uk/upnpTube#8]
While trying to cast from youtube app on phone. I get this:
```
Connected to Phone
[object Object]
[yt-cast-receiver.YouTubeApp] Command #7 - setPlaylist received with the following data:
{
  ctt: 'APmki7Qd8zMFAQjKvM689uWBanoFPAMXHfSF4h9FT_DycM1T7FRVSRXlDsc9jkZaE20qzg3R2By6R_LFl2OI_JRzIp-qGeE9TbvfCKEvV7_b60fQCLit9HqL9T6NV2AZWxHrCKKXPBu8',
  sourceDeviceType: 'REMOTE_CONTROL',
  videoId: 'LXb3EKWsInQ',
  playerParams: 'YADIAQCQAgE=',
  params: 'qgMKdGVzdCB2aWRlb7oDCgiH9_H78u6zoAu6AwsIqbb78sSLiKSaAboDCgjYuOuOmtCSsx66AwsIi4_3mKftm7zCAboDCwiygoKh-6Wb4cUBugMKCPjg9Z7t04KOI7oDCwiUprj_75yz3rQBugMLCPrl2Kn83u7IvAG6AwsIkMuEjevxwqvAAboDCgj6_cDVzdKax2K6AwoI7sG1mOGTv-x_ugMKCJm2idy6xuSJLroDCwirm--h-eWky7ABugMLCJ_U4uLJyYPI2AG6AwsIwM-f1Kvc6YP7AboDCgiut5Wy4_G4zQ26AwsIuvDnn9Su-9zXAboDCgjzyNrmgv307yW6AwoIna2NlpTAztZ1ugMLCOmX85rz4N22uQG6AwoI07DFw6epyL4FugMLCOvrp4fGsO7L6AG6AwoImKmH9IPtpKQeugMKCMW5krbs1aTcI7oDCgiCqpzp8-Dt5Wi6AwoI75DF8tKUsZlMugMLCPuN4vSfv6WAzAG6AwsI4YDAqq7E0r3YAboDCgj9i7fchIGGhHO6AwoItd2dl6Knj9sBugMLCJLklfnR-6Xz2gG6AwsIr7m63ITe1qiUAboDCgiT0_Sx2aqfrUm6AwoIgKvS7bOyhotn8gMFDSGWPj8=',
  currentIndex: '0',
  listId: 'RQ3UXfZm75nwvmi4wHxuYjOcHKZD4',
  currentTime: '0',
  eventDetails: '{"videoId":"LXb3EKWsInQ","eventType":"VIDEO_ADDED","userAvatarUri":"https://yt3.ggpht.com/yti/AHXOFjUhKYVkUodD2sXd3edffcFK2pF6faW9oozkcw=s240","user":"Guy"}',
  clickTrackingParams: '',
  audioOnly: 'false',
  prioritizeMobileSenderPlaybackStateOnConnection: 'true',
  videoIds: 'LXb3EKWsInQ',
  csn: 'tyoRlz9ZLXoSlKAMI9g77Q=='
}
[yt-cast-receiver.YouTubeApp] Requesting player to play video ID LXb3EKWsInQ at position 0s
[yt-cast-receiver.YouTubeApp] Reporting change in player state...
[🔊 Living Room (Denon Denon AVR-X3400H)]: getPosition
[🔊 Living Room (Denon Denon AVR-X3400H)]: getDuration
[🔊 Living Room (Denon Denon AVR-X3400H)]: Play LXb3EKWsInQ at position 0s
[🔊 Living Room (Denon Denon AVR-X3400H)]: getPosition error:
Error: Service urn:upnp-org:serviceId:AVTransport not provided by device
    at /home/user/src/upnpTube/node_modules/upnp-device-client/index.js:63:17
    at /home/user/src/upnpTube/node_modules/upnp-device-client/index.js:38:7
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'ENOSERVICE'
}
[🔊 Living Room (Denon Denon AVR-X3400H)]: getDuration error:
Error: Service urn:upnp-org:serviceId:AVTransport not provided by device
    at /home/user/src/upnpTube/node_modules/upnp-device-client/index.js:63:17
    at /home/user/src/upnpTube/node_modules/upnp-device-client/index.js:38:7
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'ENOSERVICE'
}
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Service urn:upnp-org:serviceId:AVTransport not provided by device
    at /home/user/src/upnpTube/node_modules/upnp-device-client/index.js:63:17
    at /home/user/src/upnpTube/node_modules/upnp-device-client/index.js:38:7
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'ENOSERVICE'
}

Node.js v19.7.0`
```

**Comment by mas94uk** [comment]
I'm not sure what's going on there. Looks like the device doesn't support reporting the duration or position, but I'm not quite sure why it crashes. Does it properly crash out, exit the program? Does it happen every time, or intermittently?

**Comment by BodingClockchian** [comment]
Getting the same error with an denon 1700. Happens every time. And yes is does end the program

**Comment by ihor-mutel** [comment]
Getting the same error on sonos one

**Comment by johnyfrol** [comment]
getting same error on SYMFONISK
